### ISSUE TITLE
Investigate options for data retrieval

### ISSUE THREAD

**Issue by iwilson001** [jacob-wilkens/show-notifications#1]
MAL, IMDb, etc
https://rapidapi.com/linaspurinis/api/mdblist/
https://rapidapi.com/unogs/api/unogs/
https://rapidapi.com/felixeschmittfes/api/myanimelist/

**Comment by jacob-wilkens** [comment]
this api seems to be the best in terms of data and access 
https://developer.themoviedb.org/reference/intro/getting-started

this package is a ts wrapper for it
https://www.npmjs.com/package/tmdb-ts

**Comment by iwilson001** [comment]
Found this scraper for MAL [MALScraper](https://www.npmjs.com/package/mal-scraper), it would allow us to get anime by season (aka if it's spring, get all summer anime) the data returned comes with the release date of the show
